#!/bin/bash

#vars
BASEDIR="/opt/incursion-bot/"
RUNDIR="/opt/incursion-bot/run/"
IMAGEDIR="/opt/incursion-bot/image/"
EXECFILE="jabber.dll"
UPDATE_EXIT_CODE=9567

# Remove the content of the
rm -rf $RUNDIR*
mkdir $RUNDIR
cp -r $IMAGEDIR* $RUNDIR
cd $RUNDIR/publish

IS_DEPLOYMENT=true dotnet $EXECFILE

if [ "$?" -eq "$UPDATE_EXIT_CODE" ]
then
    exit 0
else
    exit $?
fi