#!/bin/sh

#vars
BASEDIR="/opt/incursion-bot/"
RUNDIR="/opt/incursion-bot/run/"
IMAGEDIR="/opt/incursion-bot/image/"
EXECFILE="jabber.dll"


# Remove the content of the 
rm -rf $RUNDIR*

cp $IMAGEDIR $RUNDIR

dotnet $RUNDIR$EXECFILE